#!/usr/bin/env bash
# PostToolUse formatter for source files this repository will eventually hold.
#
# Only fires for web-source extensions. It deliberately does NOT touch .json or
# .md: images-optimizado/manifest.json is generated by tools/manifest.pl, and
# reformatting it would create churn against the pipeline that owns it.
#
# IMPORTANT: hooks run in a non-interactive shell that does NOT inherit shell
# aliases, functions, or an nvm-activated PATH. Prettier is therefore located
# explicitly rather than assumed to be on PATH.
set -uo pipefail

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

payload=$(cat)
file=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // .tool_response.filePath // ""')

[ -n "$file" ] || exit 0
[ -f "$file" ] || exit 0

case "$file" in
  *.tsx|*.ts|*.jsx|*.js|*.mjs|*.cjs|*.css|*.scss) ;;
  *) exit 0 ;;
esac

# Locate a formatter, preferring the project-local one so the repo's pinned
# version wins over a global install. Order: project-local, PATH, then any
# nvm-managed node. If none exists, do nothing — the site app does not exist
# yet and this must stay a no-op rather than an error on every edit.
formatter=""

root=$(git -C "$(dirname "$file")" rev-parse --show-toplevel 2>/dev/null || true)
if [ -n "$root" ] && [ -x "$root/node_modules/.bin/prettier" ]; then
  formatter="$root/node_modules/.bin/prettier"
fi

if [ -z "$formatter" ] && command -v prettier >/dev/null 2>&1; then
  formatter=$(command -v prettier)
fi

if [ -z "$formatter" ]; then
  for candidate in "$HOME"/.nvm/versions/node/*/bin/prettier; do
    [ -x "$candidate" ] && formatter="$candidate"
  done
fi

[ -n "$formatter" ] || exit 0

"$formatter" --write --ignore-unknown "$file" >/dev/null 2>&1 || true
exit 0
