#!/usr/bin/env bash
# post_tool_call formatter for source files in the Casa Alta repository.
#
# Hermes wire protocol (agent/shell_hooks.py):
#   stdin  {"hook_event_name":"post_tool_call","tool_name":"write_file",
#           "tool_input":{"path":"...","content":"..."},"cwd":"...","profile":"..."}
#   stdout invalid JSON logs a warning; this hook writes nothing and exits 0.
#
# TWO DIFFERENCES FROM THE CLAUDE CODE HOOK THIS REPLACES:
#   1. Hermes's `matcher` is a regex on the TOOL NAME, so this is registered for
#      `write_file|patch` instead of `Write|Edit`.
#   2. Hermes names the file argument `path`, not `file_path`. Both spellings are
#      read below so the script survives either.
#
# Registered GLOBALLY in ~/.hermes/config.yaml, so it self-scopes: it only
# formats files that live inside the repository this script lives in. In any
# other project it exits 0 without touching anything.
#
# Only fires for web-source extensions. It deliberately does NOT touch .json or
# .md: images-optimizado/manifest.json is generated by tools/manifest.pl, and
# reformatting it would create churn against the pipeline that owns it.
#
# IMPORTANT: hooks run in a non-interactive shell that does NOT inherit shell
# aliases, functions, or an nvm-activated PATH. Prettier is therefore located
# explicitly rather than assumed to be on PATH.
set -uo pipefail

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

payload=$(cat)
file=$(printf '%s' "$payload" | jq -r '.tool_input.path // .tool_input.file_path // ""')

[ -n "$file" ] || exit 0
[ -f "$file" ] || exit 0

case "$file" in
  *.tsx | *.ts | *.jsx | *.js | *.mjs | *.cjs | *.css | *.scss) ;;
  *) exit 0 ;;
esac

# Scope gate: only format inside this repository.
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd) || exit 0
repo_root=$(cd -- "$script_dir/../.." && pwd) || exit 0

abs_file=$(cd -- "$(dirname -- "$file")" 2>/dev/null && printf '%s/%s' "$(pwd)" "$(basename -- "$file")") || exit 0
case "$abs_file" in
  "$repo_root"/*) ;;
  *) exit 0 ;;
esac

# Locate a formatter, preferring the project-local one so the repo's pinned
# version wins over a global install. Order: project-local, PATH, then any
# nvm-managed node. If none exists, do nothing -- an unavailable formatter must
# stay a no-op rather than an error on every edit.
formatter=""

if [ -x "$repo_root/node_modules/.bin/prettier" ]; then
  formatter="$repo_root/node_modules/.bin/prettier"
fi

if [ -z "$formatter" ] && command -v prettier >/dev/null 2>&1; then
  formatter=$(command -v prettier)
fi

if [ -z "$formatter" ]; then
  for candidate in "$HOME"/.nvm/versions/node/*/bin/prettier; do
    [ -x "$candidate" ] && formatter="$candidate"
  done
fi

[ -n "$formatter" ] || exit 0

"$formatter" --write --ignore-unknown "$abs_file" >/dev/null 2>&1 || true
exit 0
