/**
 * Mirrors images-optimizado/manifest.json exactly.
 *
 * Written by hand rather than inferred, because the manifest is generated by
 * tools/manifest.pl and these names are its contract. Two things about it are
 * easy to get wrong and are called out here so nobody re-derives them:
 *
 *  - `tiers: [480, 960]` is the LONG EDGE. The `srcset` `w` descriptor is the
 *    ACTUAL width. A 1200x1600 portrait reports 360/720/1200 while its files are
 *    still named -480/-960. Never assume `variants[i].width === tiers[i]`.
 *  - `variants` is variable length. 22 photos have only a -480, and two project
 *    covers have no -960 at all.
 */

export interface ManifestVariant {
  width: number;
  height: number;
  file: string;
}

export interface ManifestPhoto {
  /** Zero-padded string, not a number. */
  order: string;
  slug: string;
  /** 1..5, assigned during the human ranking pass. */
  score: number;
  /** Spanish description of what is visible; doubles as alt text source. */
  note: string;
  /** Path inside images/ of the untouched original. */
  source: string;
  /** Filename stem: "<order>-<slug>". */
  base: string;
  full: ManifestVariant;
  fallback: string;
  variants: ManifestVariant[];
  /** Authoritative responsive string. Parse or pass through; never rebuild. */
  srcset: string;
}

export interface ManifestProject {
  /** "<order>-<slug>", e.g. "02-el-bicho". */
  dir: string;
  order: string;
  slug: string;
  photos: ManifestPhoto[];
}

export interface Manifest {
  avif_quality: number;
  base: string;
  generated: string;
  note: string;
  tiers: number[];
  stats: { projects: number; photos: number };
  projects: ManifestProject[];
}
