import type { Plugin } from "@opencode-ai/plugin"
import { execFileSync } from "node:child_process"
import { appendFileSync, existsSync, mkdirSync, readdirSync } from "node:fs"
import { homedir } from "node:os"
import { basename, dirname, isAbsolute, join } from "node:path"

// Casa Alta repository guard. Ports the two Hermes shell hooks that used to
// live in .hermes/hooks/ and adds the git-conventions skill gate and the
// dirty-tree watchdog. A project plugin under .opencode/plugins/ only loads in
// this repository, so the global self-scope gate the shell scripts needed is
// gone.

// Repo policy: AI attribution is forbidden in commit messages.
const ATTRIBUTION = /co-authored-by|generated with|noreply@anthropic\.com/i

// Only web-source extensions are formatted. .json and .md are deliberately
// excluded: images-optimizado/manifest.json is generated by tools/manifest.pl
// and reformatting it churns against the pipeline that owns it.
const FORMATTABLE = /\.(tsx|ts|jsx|js|mjs|cjs|css|scss)$/

const EDIT_TOOLS = new Set(["edit", "write"])

// Version-control hygiene is owned by the `git-conventions` skill. Any command
// that mutates the index or the working tree is gated on that skill having been
// loaded in the current session, so its rules cannot be skipped by not loading
// it. `git status`/`diff`/`log` and friends stay ungated.
const GIT_MUTATIONS = new Set(["add", "commit", "mv", "rm"])

const SKILL_TO_LOAD = "git-conventions"

// Session-scoped bookkeeping. The plugin instance lives for the server
// lifetime; a restart clears it, which is correct -- a new session must load
// the skill again.
const skillLoaded = new Set<string>()
const dirtyWarned = new Map<string, string>()

const GIT_GLOBAL_FLAGS_WITH_VALUE = new Set([
  "-C",
  "-c",
  "--git-dir",
  "--work-tree",
  "--namespace",
  "--exec-path",
  "--config-env",
])

function gitMutation(cmd: string): boolean {
  // Split compound commands so `cd x && git add .` is inspected segment by
  // segment, then look for `git` followed by a mutation subcommand, skipping
  // any global flags (and their values) that sit between them.
  for (const segment of cmd.split(/&&|\|\||[;|\n]/)) {
    const tokens = segment.trim().split(/\s+/)
    const at = tokens.indexOf("git")
    if (at === -1) continue
    let i = at + 1
    while (i < tokens.length && tokens[i].startsWith("-")) {
      i += GIT_GLOBAL_FLAGS_WITH_VALUE.has(tokens[i]) ? 2 : 1
    }
    if (GIT_MUTATIONS.has(tokens[i] ?? "")) return true
  }
  return false
}

function git(root: string, args: string[], input?: string): string {
  try {
    return execFileSync("git", args, {
      cwd: root,
      encoding: "utf8",
      input: input ?? "",
      stdio: ["pipe", "pipe", "ignore"],
      maxBuffer: 8 * 1024 * 1024,
    })
  } catch {
    // A non-zero git exit means "nothing to inspect", not a failure worth
    // surfacing. The guard must never block a commit because git hiccuped.
    return ""
  }
}

// Identifies a path by its two numeric prefixes: the project folder and the
// photo's own ordinal. Both are published. `01-plaza/02-fachada.avif` -> "01|02".
function numPrefix(path: string): string {
  const dir = (basename(dirname(path)).match(/^\d+/) ?? [""])[0]
  const base = (basename(path).match(/^\d+/) ?? [""])[0]
  return `${dir}|${base}`
}

function badRenames(root: string): string[] {
  // -M40% so a rename whose content also changed (a re-encoded photo) still
  // reports as a rename rather than as delete+add.
  const out = git(root, ["diff", "--cached", "--name-status", "-M40%", "--diff-filter=R"])
  const bad: string[] = []
  for (const line of out.split("\n")) {
    if (!line.trim()) continue
    const [, oldPath, newPath] = line.split("\t")
    if (!newPath) continue
    if (numPrefix(oldPath) !== numPrefix(newPath)) bad.push(`  ${oldPath} -> ${newPath}`)
  }
  return bad
}

function stagedNames(root: string, pathspec?: string): string[] {
  const args = ["diff", "--cached", "--name-only"]
  if (pathspec) args.push("--", pathspec)
  return git(root, args).split("\n").filter(Boolean)
}

// Byte weight of what is staged, binaries included.
//
// NOT `--numstat`: it reports binary files as "-", which coerces to 0, so a
// weight check built on it can never fire on an image commit. `--raw` yields
// the new blob hash per path and `cat-file` reports its real size.
function stagedAddedBytes(root: string): number {
  const raw = git(root, ["diff", "--cached", "--raw", "--diff-filter=AM"])
  const shas = raw
    .split("\n")
    .map((line) => line.split(/\s+/))
    .filter((cols) => cols.length >= 4)
    .map((cols) => cols[3])
    .filter(Boolean)
  if (!shas.length) return 0
  const out = git(root, ["cat-file", "--batch-check=%(objectsize)"], shas.join("\n"))
  return out.split("\n").reduce((sum, line) => {
    const n = Number.parseInt(line, 10)
    return sum + (Number.isFinite(n) ? n : 0)
  }, 0)
}

function findFormatter(root: string): string | null {
  const local = join(root, "node_modules", ".bin", "prettier")
  if (existsSync(local)) return local
  try {
    const found = execFileSync("which", ["prettier"], { encoding: "utf8" }).trim()
    if (found) return found
  } catch {}
  try {
    const base = join(homedir(), ".nvm", "versions", "node")
    for (const version of readdirSync(base)) {
      const candidate = join(base, version, "bin", "prettier")
      if (existsSync(candidate)) return candidate
    }
  } catch {}
  return null
}

export const CasaAltaPlugin: Plugin = async ({ worktree, directory, client }) => {
  const root = worktree || directory || process.cwd()

  const logWarning = (file: string, message: string) => {
    try {
      const logDir = join(root, ".opencode", "logs")
      mkdirSync(logDir, { recursive: true })
      appendFileSync(join(logDir, file), `${new Date().toISOString()}\t${message.replace(/\n/g, " ")}\n`)
    } catch {}
  }

  return {
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "bash") return
      const cmd = typeof output.args?.command === "string" ? output.args.command : ""

      // Gate on the git-conventions skill. Enforced before any other check:
      // a staging or commit command run without the skill is the thing this
      // rule exists to prevent.
      if (gitMutation(cmd) && !skillLoaded.has(input.sessionID)) {
        throw new Error(
          "Blocked: load the `git-conventions` skill before staging or committing anything " +
            "in this repository. Call the skill tool with name 'git-conventions', follow its " +
            "hazard checks and work-unit grouping, then retry the command.",
        )
      }

      if (!cmd.includes("git commit")) return

      // 1. AI attribution. Inspect only the command string: a pre-execution
      //    hook cannot see an editor-typed message, and `-m` is how commits are
      //    composed here.
      if (ATTRIBUTION.test(cmd)) {
        throw new Error(
          "Blocked: this repository forbids AI attribution trailers (Co-Authored-By, " +
            "'Generated with', noreply@anthropic.com). Commit history here is " +
            "conventional-commits only. Remove the trailer and commit again.",
        )
      }

      // 2. Renumbering a published path. The <NN> prefix is in published URLs;
      //    reordering belongs in manifest.json `order`, never a filesystem path.
      const renames = badRenames(root)
      if (renames.length) {
        throw new Error(
          "Blocked: staged rename changes a numeric prefix, which is part of a published URL:\n" +
            renames.join("\n") +
            "\nRenaming a published project or photo breaks its link and discards search " +
            "ranking. Record the new order in manifest.json as the 'order' field instead.",
        )
      }

      // 3. Modifying a tracked file under images/. images/ is read-only source.
      //    New raw photos are fine; changes to files already committed there are
      //    always a mistake.
      const mutations = git(root, [
        "diff",
        "--cached",
        "--name-status",
        "--diff-filter=MDRT",
        "--",
        "images/",
      ]).trim()
      if (mutations) {
        throw new Error(
          "Blocked: staged changes modify files already tracked under images/, which is " +
            "read-only source material:\n" +
            mutations +
            "\nAdding new raw photos is fine. Modifying or deleting existing ones is not -- " +
            "restore them and stage only the additions.",
        )
      }

      // 4. Generated-output churn and weight. opencode has no in-band warning
      //    channel on tool.execute.before, so this goes to stderr and to a
      //    repo-local log the human can read. The denials above are unaffected.
      const staged = stagedNames(root)
      const optimized = stagedNames(root, "images-optimizado/")
      const addedMb = Math.floor(stagedAddedBytes(root) / 1048576)
      const notes: string[] = []
      if (optimized.length > 50) {
        notes.push(
          `${optimized.length} files staged under images-optimizado/. Re-running the pipeline ` +
            "rewrites broadly; confirm this is the intent and not a stray 'git add -A'.",
        )
      }
      if (addedMb >= 20) {
        notes.push(
          `~${addedMb} MB of new content staged. There is no Git LFS and no .gitattributes ` +
            "here, so this becomes permanent history.",
        )
      }
      if (notes.length) {
        const message =
          `git-guard: ${staged.length} file(s) staged.\n` + notes.map((n) => `- ${n}`).join("\n")
        logWarning("git-guard.log", message)
        console.error(message)
      }
    },

    "tool.execute.after": async (input) => {
      // Record a successful skill load. `tool.execute.after` only runs when the
      // tool actually executed, so a denied or failed load does not unlock the
      // staging/commit gate.
      if (input.tool === "skill" && input.args?.name === SKILL_TO_LOAD) {
        skillLoaded.add(input.sessionID)
        return
      }

      if (!EDIT_TOOLS.has(input.tool)) return
      const filePath = input.args?.filePath
      if (typeof filePath !== "string" || !FORMATTABLE.test(filePath)) return
      const abs = isAbsolute(filePath) ? filePath : join(root, filePath)
      if (!existsSync(abs)) return
      const formatter = findFormatter(root)
      // An unavailable formatter stays a no-op rather than an error on every edit.
      if (!formatter) return
      try {
        execFileSync(formatter, ["--write", "--ignore-unknown", abs], { stdio: "ignore" })
      } catch {}
    },

    event: async ({ event }) => {
      // A dirty tree at session idle means work was left uncommitted. This is
      // a warning, not a block -- it can only run when the session is already
      // idle -- so it nudges toward a deliberate commit without ever committing
      // on the human's behalf.
      if (event.type !== "session.idle") return
      const dirty = git(root, ["status", "--porcelain"]).trim()
      if (!dirty) {
        dirtyWarned.delete(event.properties.sessionID)
        return
      }
      // One warning per distinct dirty state, so repeated idle events do not
      // spam the toast while nothing has changed.
      if (dirtyWarned.get(event.properties.sessionID) === dirty) return
      dirtyWarned.set(event.properties.sessionID, dirty)

      const count = dirty.split("\n").length
      const message = `working tree is not clean: ${count} path(s) uncommitted.`
      logWarning("dirty-tree.log", message)
      console.error(`git-conventions: ${message}`)
      try {
        await client.tui.showToast({
          body: {
            title: "Working tree not clean",
            message: `${count} uncommitted path(s). Load git-conventions and commit deliberately.`,
            variant: "warning",
            duration: 8000,
          },
        })
      } catch {}
    },
  }
}
